### ISSUE TITLE
"Invalid Token" when querying feature layer

### ISSUE THREAD

**Issue by spaceof7** [Esri/arcgis-python-api#1116]
Using v1.9.1, when i query a specific feature layer i get the following error:
```python
from arcgis.gis import GIS

agol = GIS(profile='agol')
kc_fs= agol.content.get('0105102628644125bc335e07b9a9e40a')
k = kc_fs.layers[0]
k.query(q)
```
```python
Traceback (most recent call last):

  File "/home/andrew/miniconda3/envs/arcgis/lib/python3.7/site-packages/arcgis/features/layer.py", line 2989, in _query
    postdata=params,

  File "/home/andrew/miniconda3/envs/arcgis/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1079, in post
    force_bytes=kwargs.pop("force_bytes", False),

  File "/home/andrew/miniconda3/envs/arcgis/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py", line 607, in _handle_response
    raise Exception(data["error"])

Exception: {'code': 498, 'message': 'Invalid Token', 'details': []}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/tmp/ipykernel_473907/3273536438.py", line 1, in <module>
    k.query(q)

  File "/home/andrew/miniconda3/envs/arcgis/lib/python3.7/site-packages/arcgis/features/layer.py", line 1736, in query
    record_count = self._query(url, params, raw=as_raw)

  File "/home/andrew/miniconda3/envs/arcgis/lib/python3.7/site-packages/arcgis/features/layer.py", line 2996, in _query
    if queryException.args[0].lower().find("invalid token") > -1:

AttributeError: 'dict' object has no attribute 'lower'
```

This may be related to bug #776. That fix for never worked in this case.  This error does not occur in 1.8.1.

The source data for this feature layer is not hosted in our AGOL but on the local county's server.  The item was added to our AGOL using the URL of the county's ArcGIS Server. I get this error when i try to get the feature layer from our AGOL item:
```python
from arcgis.gis import GIS

agol = GIS(profile='agol')
kc_parcels_id = '0105102628644125bc335e07b9a9e40a'
kc_fs= agol.content.get(kc_parcels_id)
k = kc_fs.layers[0]
k.query(q)
```

 if i first define a GIS object but don't use it and get the feature layer directly I also get the error:
```python
from arcgis.gis import GIS
from arcgis.features import FeatureLayer

agol = GIS(profile='agol')
f = FeatureLayer('https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer/2')
f.query(q)
```
However, when i create a feature layer accessing the county's server directly AND without defining a GIS object, the query is successful.
```python
from arcgis.features import FeatureLayer

f = FeatureLayer('https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer/2')
f.query(q)
```

**Comment by achapkowski** [comment]
The item id is no longer working so I tested with the URLs:

```
from arcgis.gis import GIS
from arcgis.features import FeatureLayer
agol = GIS(profile='agol')
f = FeatureLayer('https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer/2', gis=agol)
f.query()
```
This works in 2.0.0 and the upcoming release of 2.0.1.
