### ISSUE TITLE
ArcGIS pro 2.8 (Versão avaliação gratuita Trial) falha no Train Deep Learning Model

### ISSUE THREAD

**Issue by b-rangel** [Esri/arcgis-python-api#1136]
**Após realizar a rotulação de objetos passo a realizar a utilização da ferramenta Train Deep Learning Model, entranto após os ajustes de parâmetros ocorre a seguinte série de erros:**

Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 297, in <module>
    execute()
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 241, in execute
    data_bunch = prepare_data(in_folder, **prepare_data_kwargs)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\arcgis\learn\_data.py", line 1558, in prepare_data
    .label_from_func(get_y_func)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\fastai\data_block.py", line 475, in _inner
    self.train = ft(*args, from_item_lists=True, **kwargs)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\fastai\data_block.py", line 299, in label_from_func
    return self._label_from_list([func(o) for o in self.items], label_cls=label_cls, **kwargs)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\fastai\data_block.py", line 299, in <listcomp>
    return self._label_from_list([func(o) for o in self.items], label_cls=label_cls, **kwargs)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\arcgis\learn\_data.py", line 232, in _get_bbox_lbls
    return _get_bbox_classes(label_file, class_mapping, height_width, dataset_type=dataset_type)
  File "C:\Users\x893757\AppData\Local\ESRI\conda\envs\deeplearning-clone\Lib\site-packages\arcgis\learn\_data.py", line 201, in _get_bbox_classes
    xmin, ymin, xmax, ymax = float(bnd_box.find('xmin').text), \
ValueError: could not convert string to float: '178,20'

**Alguém pode me ajudar? É urgente!** 
![Captura de tela 2021-12-23 103717](https://user-images.githubusercontent.com/96581340/147248184-bf160d6e-f729-40d5-8d49-81014cc454ec.png)

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
