### ISSUE TITLE
Unable to import ArcGIS Python library

### ISSUE THREAD

**Issue by sullivani** [Esri/arcgis-python-api#1169]
**Describe the bug**
Trying to import the ArcGIS library, I encounter an error.

**To Reproduce**
```python
from arcgis.gis import GIS
```
error:
```python
Traceback (most recent call last): 
  File ".\main.py", line 1, in <module>                                                                                                  
    from arcgis.gis import GIS
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\__init__.py", line 4, in <module>
    from . import features, geoanalytics, geocoding, geometry
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\features\__init__.py", line 26, in <module>
    from .feature import Feature, FeatureSet, FeatureCollection
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\features\feature.py", line 25, in <module>
    from arcgis.gis import Layer
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\gis\__init__.py", line 31, in <module>
    from arcgis.gis._impl._con._helpers import _is_http_url
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\gis\_impl\_con\__init__.py", line 1, in <module>
    from ._connection import Connection
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 26, in <module>
    certifi_win32.generate_pem()
  File "C:\Users\user\PycharmProjects\sqm_arcgis\venv\lib\site-packages\certifi_win32\wincerts.py", line 113, in generate_pem
    os.makedirs(os.path.dirname(PEM_PATH))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\user\\AppData\\Local\\.certifi'
```

**Platform**
 - OS: Windows 10
 - Python API Version: 3.8 and 3.7
 - ArcGIS Python API: 1.9.1

**Additional context**
This issue only seems to occur on Windows 10. I have even tried this on multiple Windows 10 machines, but the same error occurs.
I have tried reinstalling both Python and the ArcGIS libraries, but still the same error occurs.
This issue does not appear to occur on Linux as I was able to import the ArcGIS library without this error occuring.

**Installed Packages**
```
Package                 Version
----------------------- ---------
anyio                   3.5.0
arcgis                  1.9.1
argon2-cffi             20.1.0
async-generator         1.10
asyncio                 3.4.3
attrs                   20.3.0
Babel                   2.9.1
backcall                0.2.0
beautifulsoup4          4.9.3
bleach                  3.3.0
cachetools              5.0.0
certifi                 2020.11.8
cffi                    1.14.5
chardet                 3.0.4
charset-normalizer      2.0.3
click                   7.1.2
click-plugins           1.1.1
cligj                   0.7.1
cloudpickle             1.6.0
colorama                0.4.4
cryptography            36.0.1
cycler                  0.10.0
dask                    2.19.0
decorator               5.0.6
defusedxml              0.7.1
distributed             2.19.0
entrypoints             0.3
et-xmlfile              1.0.1
Fiona                   1.8.19
flexpolyline            0.1.0
GDAL                    3.2.3
GeoAlchemy2             0.8.5
geojson                 2.5.0
geomet                  0.3.0
geopandas               0.9.0
greenlet                1.0.0
HeapDict                1.0.1
idna                    2.10
importlib-metadata      3.10.1
ipykernel               5.5.3
ipython                 7.22.0
ipython-genutils        0.2.0
ipywidgets              7.6.3
isoweek                 1.3.3
jdcal                   1.4.1
jedi                    0.18.0
Jinja2                  2.11.3
json5                   0.9.6
jsonschema              3.2.0
jupyter                 1.0.0
jupyter-client          6.1.12
jupyter-console         6.4.0
jupyter-core            4.7.1
jupyter-server          1.13.4
jupyterlab              3.2.8
jupyterlab-pygments     0.1.2
jupyterlab-server       2.10.3
jupyterlab-widgets      1.0.0
keyring                 21.7.0
kiwisolver              1.3.1
lerc                    0.1.0
MarkupSafe              1.1.1
matplotlib              3.4.1
mistune                 0.8.4
modin                   0.8.3
msgpack                 1.0.2
munch                   2.5.0
nbclassic               0.3.5
nbclient                0.5.3
nbconvert               6.0.7
nbformat                5.1.3
nest-asyncio            1.5.1
notebook                6.3.0
ntlm-auth               1.5.0
numpy                   1.21.1
oauthlib                3.2.0
openpyxl                3.0.7
packaging               20.8
pandas                  1.3.1
pandocfilters           1.4.3
parso                   0.8.2
pickleshare             0.7.5
Pillow                  8.2.0
pip                     21.1.1
prometheus-client       0.10.1
prompt-toolkit          3.0.18
psutil                  5.8.0
psycopg2-binary         2.9.1
pycparser               2.20
Pygments                2.8.1
pyodbc                  4.0.31
pyparsing               2.4.7
pypiwin32               223
pyproj                  3.1.0
pyrsistent              0.17.3
pyshp                   2.2.0
pyspnego                0.3.1
python-certifi-win32    1.6
python-dateutil         2.8.1
pytz                    2020.4
pywin32                 300
pywin32-ctypes          0.2.0
pywinpty                0.5.7
PyYAML                  5.3.1
pyzmq                   22.0.3
qtconsole               5.0.3
QtPy                    1.9.0
requests                2.26.0
requests-kerberos       0.14.0
requests-negotiate-sspi 0.5.2
requests-ntlm           1.1.0
requests-oauthlib       1.3.1
requests-toolbelt       0.9.1
Rtree                   0.9.7
selenium                3.141.0
Send2Trash              1.5.0
setuptools              40.8.0
setuptools-scm          6.4.2
Shapely                 1.7.1
six                     1.15.0
sniffio                 1.2.0
sortedcontainers        2.3.0
soupsieve               2.2.1
SQLAlchemy              1.4.22
tblib                   1.7.0
terminado               0.9.4
testpath                0.4.4
tomli                   2.0.0
toolz                   0.11.1
tornado                 6.1
traitlets               5.0.5
typing-extensions       3.7.4.3
ujson                   5.1.0
urllib3                 1.25.11
wcwidth                 0.2.5
webencodings            0.5.1
websocket-client        1.2.3
widgetsnbextension      3.5.1
winkerberos             0.8.0
wrapt                   1.13.3
zict                    2.0.0
zipp                    3.4.1
```

**Comment by achapkowski** [comment]
How did you create your environment?

**Comment by achapkowski** [comment]
We cannot reproduce your issue, please try to reinstall the library again.
