### ISSUE TITLE
Problem w/ api_key => token issues

### ISSUE THREAD

**Issue by micdup** [Esri/arcgis-python-api#1182]
**Describe the bug**
related to previous issue #1145 for which the answer did not seems right..
and since we got new facts proving there's something fishy about token management when using api key,
arcgis@2.0.0 fixed for one case (service 'elevation') but broke the other (service 'landsat'),
while behaviour w/ arcgis@1.9.1 is the opposite..

**To Reproduce**
1. run this code with your api key and test on the 2 specified services ('landsat' & 'elevation') + on arcgis@1.9.1 & arcgis@2.0.0:
```py
from arcgis import GIS
from arcgis.raster import ImageryLayer
from arcgis.raster.functions import extract_band

ARCGIS_SERVICES = {
    "landsat": "https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer",
    "elevation": "https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer",
}

service_url = ARCGIS_SERVICES['landsat']

gis = GIS(api_key="<API_KEY>")
img_layer = ImageryLayer(url=service_url, gis=gis)
layer = extract_band(img_layer, None)
lon_min, lat_max, lon_max, lat_min = (1.34, 49.85, 3.34, 47.85)
layer.extent = {"ymin": lat_min, "ymax": lat_max, "xmin": lon_min, "xmax": lon_max, "spatialReference": 4326}
raster = layer.export_image(export_format="tiff")
print('OK - got {0}'.format(raster))
```
results:

```log
#
# arcgis@1.9.1
# service_url = "https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer"
#
OK - got {'href': 'https://landsat2.arcgis.com/arcgis/rest/directories/arcgisoutput/Landsat8_Views_ImageServer/x_____xvBCm2TWNLT5mXLomno3OWA..x_____x_ags_0cb8cc0c_7abb_476f_8d49_bca86a0fb796.tif', 'width': 1200, 'height': 450, 'extent': {'xmin': -190715.77105584624, 'ymin': 6081936.35982088, 'xmax': 711690.9879683665, 'ymax': 6420338.89445496, 'spatialReference': {'wkid': 102100, 'latestWkid': 3857}}, 'scale': 0}

```

```log
#
# arcgis@1.9.1
# service_url = "https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer
#
Traceback (most recent call last):
  File "<PROJECT_DIR>/arcgis/github-token-issue.py", line 17, in <module>
    raster = layer.export_image(export_format="tiff")
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/_layer.py", line 1867, in export_image
    return self._con.post(url, params, token=self._token, timeout=None)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1041, in post
    return self._handle_response(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 595, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 618, in _handle_json_error
    raise Exception(errormessage)
Exception: Token Required
(Error Code: 499)
```

```log
#
# arcgis@2.0.0
# service_url = "https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer"
#
Traceback (most recent call last):
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/_layer.py", line 6445, in _get_service_info
    dictdata = self._con.post(self.url, params, timeout=None)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1255, in post
    return self._handle_response(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 816, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 839, in _handle_json_error
    raise Exception(errormessage)
Exception: Invalid Token
(Error Code: 498)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/_layer.py", line 6456, in _get_service_info
    dictdata = self._con.post(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1255, in post
    return self._handle_response(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 816, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 839, in _handle_json_error
    raise Exception(errormessage)
Exception: Invalid Token
(Error Code: 498)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<PROJECT_DIR>/arcgis/github-token-issue.py", line 14, in <module>
    layer = extract_band(img_layer, None)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/functions/__init__.py", line 2235, in extract_band
    return _clone_layer(layer, template_dict, raster_ra)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/functions/__init__.py", line 101, in _clone_layer
    info = layer._get_service_info()
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/raster/_layer.py", line 6465, in _get_service_info
    dictdata = self._con.post(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1255, in post
    return self._handle_response(
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 816, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "<PROJECT_DIR>/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 839, in _handle_json_error
    raise Exception(errormessage)
Exception: Invalid Token
(Error Code: 498)
```
```log
#
# arcgis@2.0.0
# service_url = "https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer"
#
OK - got {'href': 'https://elevation.arcgis.com/arcgis/rest/directories/arcgisoutput/WorldElevation/Terrain_ImageServer/x_____xfvwbMLXGeajH1sKWCU15OQ..x_____x_ags_c5f05078_c4be_4192_a7bf_effffe142bb9.tif', 'width': 1200, 'height': 450, 'extent': {'xmin': -190715.77105584624, 'ymin': 6081936.35982088, 'xmax': 711690.9879683665, 'ymax': 6420338.89445496, 'spatialReference': {'wkid': 102100, 'latestWkid': 3857}}, 'scale': 0}
```

**Expected behavior**
in arcgis@2.0.0, there should be no regression for service 'landsat' 

**Platform:**
- OS: Mac+Linux
- Python 3.9
- tested w/ arcgis@1.9.1 & arcgis@2.0.0

**Comment by achapkowski** [comment]
The elevation service does not accept the API Key. 
From the API Key doc: "API keys can only be used to access ArcGIS location services."
