### ISSUE TITLE
ArcGIS Pro 2.9.3 cloned python environment gets permission denied error after upgrading python api to 2.0

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-python-api#1248]
**Describe the bug**
In ArcGIS Pro 2.9.3 - cloned python environment gets permission denied error after upgrading python api to 2.0

**To Reproduce**
Clone the default env and upgrade arcgis python api using no pin
```python
conda upgrade -c esri --no-pin arcgis
```
error:
```python
rror processing line 1 of C:\arcgispro_envs\aap20\arcgispro-py3-clone\lib\site-packages\python-certifi-win32-init.pth:
  Traceback (most recent call last):
    File "C:\arcgispro_envs\aap20\arcgispro-py3-clone\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "C:\arcgispro_envs\aap20\arcgispro-py3-clone\lib\site-packages\certifi_win32\bootstrap.py", line 3, in <module>
      import wrapt
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 724, in exec_module
    File "<frozen importlib._bootstrap_external>", line 859, in get_code
    File "<frozen importlib._bootstrap_external>", line 916, in get_data
  PermissionError: [Errno 13] Permission denied: 'C:\\arcgispro_envs\\aap20\\arcgispro-py3-clone\\lib\\site-packages\\wrapt\\__init__.py'
Remainder of file ignored
Connected to pydev debugger (build 221.5591.52)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
PermissionError: [Errno 13] Permission denied: 'C:\\arcgispro_envs\\aap20\\arcgispro-py3-clone\\lib\\site-packages\\arcgis\\__init__.py'
python-BaseException
```

**Expected behavior**
Only the default env works. Any cloned env has issues once python api is upgraded.

**Platform (please complete the following information):**
Python IDE : PyCharm professional

**Comment by bruce-szalwinski** [comment]
What version of python are you running?

**Comment by achapkowski** [comment]
Have you tried turning the machine on and off again?  Sometimes the `certifi_win32` package which merges the Windows OS cert store with certifi (requests certificate store) hangs.

**Comment by pcsswamin** [comment]
@achapkowski - Yes have restarted the machine...also noticed it on more than one machine. One way I am getting around the issue - running PyCharm prof with elevated permissions - then the error does not happen. This is not convenient or advisable in the long run for my purposes. Thing to note is that Pycharm does not need elevated permissions to access the default python env installed with Pro.

**Comment by pcsswamin** [comment]
> What version of python are you running?

whatever ArcGIS Pro 2.9.3 installs. I am only trying to use other libraries not installed by esri and do not mess with the python version esri installs.

**Comment by achapkowski** [comment]
@pcsswamin so this could be a pycharm error.  If you run the script from python.exe <script path> does it error out?

**Comment by nanaeaubry** [comment]
Closing since no activity. We can reopen if needed.
