### ISSUE TITLE
Exception: A general error occurred: local variable 'oauth_info' referenced before assignment

### ISSUE THREAD

**Issue by jacklinke** [Esri/arcgis-python-api#1264]
**To Reproduce**

Following the example in the [Analyzing patterns in feature data](https://github.com/Esri/arcgis-python-api/blob/master/guide/04-feature-data-and-analysis/analyzing-patterns-in-feature-data.ipynb) example, I ran this code (arguments modified for public viewing):

```python
# Connect to GIS
from arcgis.gis import GIS
gis = GIS("https://myserverurl/arcgis/rest/services/", "myusername", "mypass")
```

and got the following in the repl

error:

```shell
>>> from arcgis.gis import GIS
>>> gis = GIS("https://myserverurl/arcgis/rest/services/", "myusername", "mypass")
Traceback (most recent call last):
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/_auth/_token.py", line 455, in token
    self._init_token_auth_handshake()
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/_auth/_token.py", line 319, in _init_token_auth_handshake
    oauth_state = oauth_info["oauth_state"]
UnboundLocalError: local variable 'oauth_info' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1206, in post
    resp = self._session.post(
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/api.py", line 471, in post
    return self._session.post(
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/requests/models.py", line 322, in prepare
    self.prepare_auth(auth, url)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/requests/models.py", line 558, in prepare_auth
    r = auth(self)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/_auth/_token.py", line 469, in __call__
    r.headers["X-Esri-Authorization"] = f"Bearer {self.token}"
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/_auth/_token.py", line 459, in token
    self._init_token_auth_handshake()
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/auth/_auth/_token.py", line 319, in _init_token_auth_handshake
    oauth_state = oauth_info["oauth_state"]
UnboundLocalError: local variable 'oauth_info' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 498, in __init__
    raise e
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 441, in __init__
    self._portal = _portalpy.Portal(
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_portalpy.py", line 220, in __init__
    self.get_properties(True)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_portalpy.py", line 1260, in get_properties
    raise e
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_portalpy.py", line 1240, in get_properties
    resp = self.con.post(path, self._postdata(), ssl=True)
  File "/home/jack/projectdir/venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1248, in post
    raise Exception("A general error occurred: %s" % e)
Exception: A general error occurred: local variable 'oauth_info' referenced before assignment
```

**Platform:**

 - OS: Ubuntu 20.04
 - Python API Version: arcgis 2.0.0
 - Python Version: Python 3.9.6

**Comment by nanaeaubry** [comment]
Hello,

It seems you are trying to access a server endpoint. To do analyze pattern you need to use either an Online or Enterprise Portal.

You could run into this error while using the correct portal endpoint if you have not set the security question through the browser. 

Hope this helps
