### ISSUE TITLE
Cannot initialize GIS when SAML provider is configured !

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-python-api#1278]
**Describe the bug**

I cannot initialize my ArcGIS Enterprise !

**To Reproduce**
```python
from arcgis.gis import GIS

portal_url = "https://myorgportal.company.com/portal"
portal_username = "admin"
portal_password = "foo"

ent_gis = GIS(portal_url, portal_username, portal_password, verify_cert=False)
```
error:
```python
Traceback (most recent call last):
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\foobar\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\foobar\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\foobar\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\foobar\Workspace\gisbackend\scripts\configure_editor_users.py", line 28, in <module>
    ent_gis = GIS(portal_url, portal_username, portal_password, verify_cert=True)
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\__init__.py", line 507, in __init__
    raise e
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\__init__.py", line 448, in __init__
    self._portal = _portalpy.Portal(
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\_impl\_portalpy.py", line 203, in __init__
    self.con = Connection(
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 311, in __init__
    self._product = self._check_product()
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 1818, in _check_product
    res = self.get(baseurl + "info", params={"f": "json"})
  File "C:\Users\foobar\Miniconda3\envs\gis\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 756, in get
    raise Exception("A general error occurred: %s" % e)
Exception: A general error occurred: Could not login. Please ensure you have valid credentials and set your security login question.
```

Our ArcGIS Enterprise 10.9.1 is configured with our SAML provider and "ArcGIS Login" disabled.
If I enabled "ArcGIS Login" then it works.
But we specifically, disabled ArcGIS Login, to be redirected straight to the IDP in order to provide an SSO experience.

**Screenshots**
When debugging the code, I found out, that the issue is that "oauth_state" is not in the auth_response:
![image](https://user-images.githubusercontent.com/11556423/174331774-fcfd9b57-411e-4405-833d-1890f38b7180.png)

Why ? The auth_url is more or less:

https://myorgportal.company.com/portal/sharing/rest/oauth2/authorize?response_type=token&client_id=arcgisonline&redirect_uri=https%3A%2F%2Fmyorgportal.company.com&state=vy8mSotnEsSoMmVpxFVs4Zhj7PHnrw&expiration=600&allow_verification=false&style=dark&locale=en-US

and in my case, as it is only coupled with an SAML IDP, it contains a form that is posting "SAMLRequest" to our SAML provider.
Thus there is no auth_state.

**Expected behavior**

Should be able to initialize GIS !!!

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.0.1

**Additional context**

I tried downgrading to 2.0.0, and with this version, I have the following error this time:

![image](https://user-images.githubusercontent.com/11556423/174333513-29e8ca10-e9f4-4995-9a0b-ae2cf5558a66.png)

**Comment by Biboba** [comment]
For information, the latest version of 'ArcGIS API for Python' working with an ArcGIS Enterprise 10.9.1 configured solely with SAML accounts is '1.9.1.

**Comment by Biboba** [comment]
Hi Python API team,
Any feedback on this bug ? 
It seems to me prettry critical as it makes the new 2.X version unusable for us.
Thanks

**Comment by achapkowski** [comment]
SAML logins are not supported, but built-in logins are.  

You can this:

```
gis = GIS(
    url="<portal>",
    username="username",
    password="password",
    use_gen_token=True,
```

Just to note, the team has tested with multiple orgs internally and cannot reproduce the bug at 10.8.1, 10.9, 10.9.1, and the upcoming release 11.

I suggest you read:https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/ and see how SAML is expected to be used.  You can also use ```GIS('pro')``` as a login method as well.

**Comment by Biboba** [comment]
Hello,

Thanks for your reply.
It's strange. I can reproduce on all my environments even a simple base deployment.
The only things required are configure SAML account and disable built-in account on ArcGIS Enterprise 10.9.1.

Note that I am not trying to login with SAML. I trying to logging using a built-in account. 

But adding 'use_gen_token' argument to the constructor did not solve the issue :)
Many thanks for your reply and suggestion. 
This argument was not required using python API < 2.0 but looking at the documentation I am under the impression it's a new one created for my use case ?

Thanks  !

**Comment by achapkowski** [comment]
It's a new parameter in 2.0.1 to handle cases like this and a few other.
