### ISSUE TITLE
Error: Could not load the dataset: Cannot convert non-finite values (NA or inf) to integer by pd.DataFrame.spatial.from_layer

### ISSUE THREAD

**Issue by hduonggithub** [Esri/arcgis-python-api#1295]
**Describe the bug**
The same code works in Arcpy 2.9/ArcGIS Pro 2.9, and after updated to ArcGIS Pro 3.0/Arcpy 3.0, the code got the below error.

error: ```
_Traceback (most recent call last):
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\arcgis\features\geo\_accessor.py", line 2688, in from_layer
    return from_layer(layer=layer)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\arcgis\features\geo\_io\serviceops.py", line 187, in from_layer
    sdf = layer.query(where=query, as_df=True)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\arcgis\features\layer.py", line 1856, in query
    df = self._query_df(url, params)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\arcgis\features\layer.py", line 3308, in _query_df
    df = df.astype(dtypes)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\generic.py", line 5799, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\dtypes\cast.py", line 1168, in astype_nansafe
    return astype_float_to_int_nansafe(arr, dtype, copy)
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\pandas\core\dtypes\cast.py", line 1213, in astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hd\AppData\Local\ESRI\conda\envs\arcgispro_py3_clone\lib\site-packages\arcgis\features\geo\_accessor.py", line 2697, in from_layer
    raise Exception("Could not load the dataset: %s" % str(e))
Exception: Could not load the dataset: Cannot convert non-finite values (NA or inf) to integer_
```

**Platform (please complete the following information):**
 - OS:  Windows 11
 - Python API Version : 2.0.1

**Comment by achapkowski** [comment]
Can you provide what layer you were using or a sample dataset?

**Comment by hduonggithub** [comment]
@achapkowski Andrew,

Let me know if you can access this layer
https://stpao.maps.arcgis.com/home/item.html?id=b01d52ea2ee84ff8a4ae72f103a4b155

I found that those empty fields (PD, SA, PO, SR, TL) are linked to another tables. Without those fields, my code works, but with them, I got the error. ArcGIS Pro 2.9/ArcPy 2.9 (I just do not know what Python API version) works no problem.

**Comment by EricSamsonCarto** [comment]
This is still a problem on 3.0.1. I am getting it on any feature service that is an integer column.

**Comment by nanaeaubry** [comment]
@EricSamsonCarto  The next release of the Python API will be in Pro 3.1.0

**Comment by sstrack265** [comment]
Do we have any idea of when a 3.1.0 release would be? And is there a suggested work around in the meantime- such as using an older version of Python API?

**Comment by EricSamsonCarto** [comment]
@sstrack265 Options are to replace the null values in the integer field(s) with an integer, or to exclude integer fields when using the .query() method. The .query() method has a parameter to specify the output fields:

https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#featurelayer#query

**Comment by skykasko** [comment]
As suggested in an [Esri Community forum post](https://community.esri.com/t5/arcgis-api-for-python-questions/intcastingnanerror-cannot-convert-non-finite/m-p/1209821), one workaround that works with version 2.0.1 of the Python API is to use `layer.query().sdf` instead of `layer.query(as_df=True)` or `pd.DataFrame.spatial.from_layer(layer)`.
