### ISSUE TITLE
cannot create working deep learning env in ArcPRO 3.0.1

### ISSUE THREAD

**Issue by tyhayward** [Esri/arcgis-python-api#1337]
I cannot create a working deep learning environment in ArcPRO 3.0.1 using either the downloadable installer or through using conda install deeplearning essentials. Both seem to fail. With a cloned environment it is "broken" and cannot be fixed. When i attempt to use deep learning tools in pro3.0.1 i get the an issue requesting cachetools module. I have installed this in a clone env but the clone is "broken". using conda I get issues where a flexible or fixed solve cannot be found. 

If i cannot get a working environment for pro 3.0.1 I will have to revert to 2.9.x unfortunately. 

@priyankatuteja @rohitgeo please help 
  
**To Reproduce**
Steps to reproduce the behavior: when trying to use an already trained model (from probably pro2.8 era.) I get a similar issue where the cachetools module is requested. I recently ran this model on the imagery it was produced on and it ran fine. When I try to run it on new imagery it consistently causes arcPro to crash (2.9.x) - even with very small batch sizes (I have an Nvidia Quadro RTX 5000 - it should be running this easily). 
```python
Error 002667  Unable to initialize python raster function with scalar arguments. [C:\Users\Thayward\AppData\Local\Temp\ArcGISProTemp9656\sentinel2_pig_model_v5_575epochs.dlpk\ArcGISObjectDetector.py]
Traceback (most recent call last):
  File "C:\Users\Thayward\AppData\Local\Temp\ArcGISProTemp9656\sentinel2_pig_model_v5_575epochs_unfreeze50.dlpk\ArcGISObjectDetector.py", line 138, in initialize
    ChildModelDetector = getattr(importlib.import_module(
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\__init__.py", line 7, in <module>
    from arcgis import features
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\__init__.py", line 26, in <module>
    from .feature import Feature, FeatureSet, FeatureCollection
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\feature.py", line 21, in <module>
    from arcgis.geometry import (
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\geometry\__init__.py", line 82, in <module>
    from .functions import *
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\geometry\functions.py", line 18, in <module>
    from arcgis.gis import GIS
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\gis\__init__.py", line 29, in <module>
    from cachetools import cached, TTLCache
ModuleNotFoundError: No module named 'cachetools'

Unable to initialize python raster function with scalar arguments.
```
error:
```python
Error 032659 updateParameters Error: Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.validate.py", line 683, in <module>
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.validate.py", line 268, in updateParameters
    import arcgis.learn
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\__init__.py", line 7, in <module>
    from arcgis import features
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\__init__.py", line 26, in <module>
    from .feature import Feature, FeatureSet, FeatureCollection
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\features\feature.py", line 21, in <module>
    from arcgis.geometry import (
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\geometry\__init__.py", line 82, in <module>
    from .functions import *
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\geometry\functions.py", line 18, in <module>
    from arcgis.gis import GIS
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\gis\__init__.py", line 29, in <module>
    from cachetools import cached, TTLCache
ModuleNotFoundError: No module named 'cachetools'
```
**Screenshots**
![image](https://user-images.githubusercontent.com/54058249/186661030-ca498332-89a2-494e-affd-16b68b1b5918.png)

**Expected behavior**

- an environment to be created that isn't broken and can be used to use deeplearning geoprocessing tools and the python API.

**Platform (please complete the following information):**
 - OS: Windows 10 n/a 
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` errors. 
 - Python version: 3.9.13

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by priyankatuteja** [comment]
@tyhayward Thanks for reaching out to us! I would recommend following the steps below for recreating a successful deep learning environment in Pro 3.0.1
1. Ensure that the Pro application is closed and the python command prompts are also closed. (this is needed for successful uninstall)
2. Uninstall Deep Learning installer (Geo to Add or Remove Programs and search for the installer, and uninstall)
3. Next uninstall ArcGIS Pro
4. Delete folder C:\Users\username\AppData\Local\ESRI\conda\pkgs
5. Delete folder ESRI: C:\Users\username\AppData\Local\ESRI (it takes too long to delete, so you can rename it to ESRIOld and put that to delete later)
6. Delete folders that start with "." for example, .cache, .keras, .jupyter etc from this path: C:\Users\username
7. Install Pro 3.0
8. Then update software to 3.0.1 patch. 
![image](https://user-images.githubusercontent.com/39754605/187115575-3e6f3a26-cda0-4468-b1b9-706f61b58e84.png)

9. Create deep learning environment using [Deep Learning Installer](https://links.esri.com/pro-deep-learning-libraries/30)
10. To verify deep learning environment, run the following commands:
```
import fastai
import torch
import arcgis
```
Run this command to check if cuda device is picked up for training a model on GPU.

```
torch.cuda.is_available()
torch.zeros((3, 224, 224)).cuda()
```

Note: If you face an error pointing to some issue with driver, you need to update driver.

**Comment by Moustafa4** [comment]
> @tyhayward Thanks for reaching out to us! I would recommend following the steps below for recreating a successful deep learning environment in Pro 3.0.1
> 
> 1. Ensure that the Pro application is closed and the python command prompts are also closed. (this is needed for successful uninstall)
> 2. Uninstall Deep Learning installer (Geo to Add or Remove Programs and search for the installer, and uninstall)
> 3. Next uninstall ArcGIS Pro
> 4. Delete folder C:\Users\username\AppData\Local\ESRI\conda\pkgs
> 5. Delete folder ESRI: C:\Users\username\AppData\Local\ESRI (it takes too long to delete, so you can rename it to ESRIOld and put that to delete later)
> 6. Delete folders that start with "." for example, .cache, .keras, .jupyter etc from this path: C:\Users\username
> 7. Install Pro 3.0
> 8. Then update software to 3.0.1 patch.
>    ![image](https://user-images.githubusercontent.com/39754605/187115575-3e6f3a26-cda0-4468-b1b9-706f61b58e84.png)
> 9. Create deep learning environment using [Deep Learning Installer](https://links.esri.com/pro-deep-learning-libraries/30)
> 10. To verify deep learning environment, run the following commands:
> 
> ```
> import fastai
> import torch
> import arcgis
> ```
> 
> Run this command to check if cuda device is picked up for training a model on GPU.
> 
> ```
> torch.cuda.is_available()
> torch.zeros((3, 224, 224)).cuda()
> ```
> 
> Note: If you face an error pointing to some issue with driver, you need to update driver.

Hello sir , I followed this steps but I still have this error" Broken environment cannot be used"

1-I installed New windows
2- download arcgis pro 3.0.0
3- update it to 3.0.1
4- open CMD as administrator
5- conda create --name geoai python 3.9.12
6- conda activate geoai
7- conda install -c esri arcgis
8-conda install -c esri deep-learning-essentials
9-conda install -c esri arcgis_learn python=3.9.12

**Comment by tyhayward** [comment]
@priyankatuteja Thank you again for the help. I followed the instructions and it is now working as it should.
