### ISSUE TITLE
Errors Trying to Install ArcGIS in Anaconda Navigator

### ISSUE THREAD

**Issue by Chilean-Chili** [Esri/arcgis-python-api#1370]
**Describe the bug**
I am running into a long list of errors trying to install ArcGIS into my Anaconda Navigator, but I believe the critical one is: ModuleNotFoundError: Required requests_ntlm not found.

**Platform (please complete the following information):**
 - Windows 10
 - Microsoft Edge
 - Python 3.9
 
**To Reproduce**
I downloaded win-64/arcgis-2.0.1-py39_2825.tar.bz2 from the website https://anaconda.org/Esri/arcgis/files?type=conda&page=1&channel=main.

Then, I placed win-64/arcgis-2.0.1-py39_2825.tar.bz2 into my user file.

Finally, I opened the Anaconda Prompt, and input the command: conda install arcgis-2.0.1-py39_2826.tar.bz2, and this is when the errors occurred. 

**Here is everything I see in the command prompt**
(base) C:\Users\Tomas>conda install arcgis-2.0.1-py39_2826.tar.bz2

Downloading and Extracting Packages
############################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Tomas\anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.
Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.
Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.

done
ERROR conda.core.link:_execute(733): An error occurred while installing package '<unknown>::arcgis-2.0.1-py39_2826'.
Rolling back transaction: done

LinkError: post-link script failed for package <unknown>::arcgis-2.0.1-py39_2826
location of failed script: C:\Users\Tomas\anaconda3\Scripts\.arcgis-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Tomas\anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.
Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 702, in start
    self.install_extensions()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.
Traceback (most recent call last):
  File "C:\Users\Tomas\anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 972, in start
    super().start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_core\application.py", line 258, in start
    self.subapp.start()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\__init__.py", line 3, in <module>
    from arcgis.auth.tools import LazyLoader
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\__init__.py", line 1, in <module>
    from .api import EsriSession
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\api.py", line 30, in <module>
    from ._auth import (
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\__init__.py", line 3, in <module>
    from ._winauth import EsriWindowsAuth, EsriKerberosAuth
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 39, in <module>
    requests_ntlm = LazyLoader("requests_ntlm", strict=True)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\auth\tools\_lazy.py", line 23, in __init__
    raise ModuleNotFoundError(f"Required {module_name} not found.")
ModuleNotFoundError: Required requests_ntlm not found.

==> script output <==
stdout: jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...
jupyter nbextension command failed: map widgets in the jupyter notebook may not work, installation continuing...

stderr:
return code: 1

()

(base) C:\Users\Tomas>

**Comment by Chilean-Chili** [comment]
To anyone who struggled with the same issues as above, I have partially solved the problem by using the command: pip install [NAME OF UNFOUND MODULE]. 

I did this until all of the required modules were installed, and then used the command: pip install arcgis, which is where I now find myself at another problem. 

I am using Anaconda, and I use Spyder 5.2.2, and now the issue I am encountering is that arcgis (specifically, the map widget) doesn't seem to work in Spyder. I have tested this code below in both Spyder and Jupyter Notebook 6.4.12, and this code does not work in Spyder but does work in Jupyter. 

#import arcgis
from arcgis.gis import GIS
gis = GIS()

map = gis.map("San Diego, CA")

Here is the error message for when I try to use this code in Spyder:

runfile('C:/Users/Tomas/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\Tomas\untitled0.py", line 5, in <module>
    map = gis.map("San Diego, CA")

  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\gis\__init__.py", line 1370, in map
    mapwidget = MapView(gis=self, mode=mode)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\widgets\_mapview\_mapview.py", line 900, in __init__
    super(MapView, self).__init__(**kwargs)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 415, in __init__
    self.open()

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 438, in open
    self.comm = Comm(**args)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 62, in __init__
    self.open(data=data, metadata=metadata, buffers=buffers)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 100, in open
    self._publish_msg(

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 71, in _publish_msg
    self.kernel.session.send(

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 844, in send
    to_send = self.serialize(msg, ident)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 718, in serialize
    content = self.pack(content)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 99, in json_packer
    return json.dumps(

  File "C:\Users\Tomas\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(

  File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\jsonutil.py", line 112, in json_default
    return obj.isoformat().replace('+00:00', 'Z')

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument


runfile('C:/Users/Tomas/ArcGIS Functionality Test.py')
Traceback (most recent call last):

  File "C:\Users\Tomas\ArcGIS Functionality Test.py", line 5, in <module>
    map = gis.map("San Diego, CA")

  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\gis\__init__.py", line 1370, in map
    mapwidget = MapView(gis=self, mode=mode)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\widgets\_mapview\_mapview.py", line 900, in __init__
    super(MapView, self).__init__(**kwargs)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 415, in __init__
    self.open()

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 438, in open
    self.comm = Comm(**args)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 62, in __init__
    self.open(data=data, metadata=metadata, buffers=buffers)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 100, in open
    self._publish_msg(

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 71, in _publish_msg
    self.kernel.session.send(

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 844, in send
    to_send = self.serialize(msg, ident)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 718, in serialize
    content = self.pack(content)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 99, in json_packer
    return json.dumps(

  File "C:\Users\Tomas\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(

  File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\jsonutil.py", line 112, in json_default
    return obj.isoformat().replace('+00:00', 'Z')

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
    if self._isdst(dt):

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument
