### ISSUE TITLE
ArcGIS Won't Work in Spyder 5.2.2

### ISSUE THREAD

**Issue by Chilean-Chili** [Esri/arcgis-python-api#1372]
I am using Anaconda, and I use Spyder 5.2.2, and the issue I am encountering is that arcgis (specifically, the map widget) doesn't seem to work in Spyder. I have tested this code below in both Spyder and Jupyter Notebook 6.4.12, and this code does not work in Spyder but does work in Jupyter.

**Code sample I used to test if arcgis was working properly:**
#import arcgis
from arcgis.gis import GIS
gis = GIS()

map = gis.map("San Diego, CA")

**Here is the error message for when I tried to use code above in Spyder:**
runfile('C:/Users/Tomas/untitled0.py')
Traceback (most recent call last):

File "C:\Users\Tomas\untitled0.py", line 5, in
map = gis.map("San Diego, CA")

File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\gis_init_.py", line 1370, in map
mapwidget = MapView(gis=self, mode=mode)

File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\widgets_mapview_mapview.py", line 900, in init
super(MapView, self).init(**kwargs)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 415, in init
self.open()

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 438, in open
self.comm = Comm(**args)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 62, in init
self.open(data=data, metadata=metadata, buffers=buffers)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 100, in open
self._publish_msg(

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 71, in _publish_msg
self.kernel.session.send(

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 844, in send
to_send = self.serialize(msg, ident)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 718, in serialize
content = self.pack(content)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 99, in json_packer
return json.dumps(

File "C:\Users\Tomas\anaconda3\lib\json_init_.py", line 234, in dumps
return cls(

File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)

File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 257, in iterencode
return _iterencode(o, 0)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\jsonutil.py", line 112, in json_default
return obj.isoformat().replace('+00:00', 'Z')

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
if self._isdst(dt):

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 291, in _isdst
dstval = self._naive_is_dst(dt)

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument

runfile('C:/Users/Tomas/ArcGIS Functionality Test.py')
Traceback (most recent call last):

File "C:\Users\Tomas\ArcGIS Functionality Test.py", line 5, in
map = gis.map("San Diego, CA")

File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\gis_init_.py", line 1370, in map
mapwidget = MapView(gis=self, mode=mode)

File "C:\Users\Tomas\anaconda3\lib\site-packages\arcgis\widgets_mapview_mapview.py", line 900, in init
super(MapView, self).init(**kwargs)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 415, in init
self.open()

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipywidgets\widgets\widget.py", line 438, in open
self.comm = Comm(**args)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 62, in init
self.open(data=data, metadata=metadata, buffers=buffers)

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 100, in open
self._publish_msg(

File "C:\Users\Tomas\anaconda3\lib\site-packages\ipykernel\comm\comm.py", line 71, in _publish_msg
self.kernel.session.send(

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 844, in send
to_send = self.serialize(msg, ident)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 718, in serialize
content = self.pack(content)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\session.py", line 99, in json_packer
return json.dumps(

File "C:\Users\Tomas\anaconda3\lib\json_init_.py", line 234, in dumps
return cls(

File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)

File "C:\Users\Tomas\anaconda3\lib\json\encoder.py", line 257, in iterencode
return _iterencode(o, 0)

File "C:\Users\Tomas\anaconda3\lib\site-packages\jupyter_client\jsonutil.py", line 112, in json_default
return obj.isoformat().replace('+00:00', 'Z')

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 222, in utcoffset
if self._isdst(dt):

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 291, in _isdst
dstval = self._naive_is_dst(dt)

File "C:\Users\Tomas\anaconda3\lib\site-packages\dateutil\tz\tz.py", line 260, in _naive_is_dst
return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument

**Comment by nanaeaubry** [comment]
Hello we do not support widgets in spyder, this would be something that spyder needs to support just like VS code does or Jupyter Notebooks

**Comment by Chilean-Chili** [comment]
@nanaeaubry  

Thank you for your response. So if that's the case, then what IDE would you recommend?

**Comment by nanaeaubry** [comment]
If the rest of the Python API works fine in Spyder then you can continue with this.
You will not be able to see the widget but you can still use the class to create maps and save them or use the WebMap class as well. 

If you would like to see the widget then we recommend using Jupyter Notebooks. 
Other IDEs that our developers use are VS code and Pycharm but neither guarantee a visual of the widget, only Jupyter Notebooks or ArcGIS Notebooks in Portal or Pro.

Hope this helps!

**Comment by Chilean-Chili** [comment]
@nanaeaubry 

You've been very helpful, thank you! 

However, now I'm running into the same error in Jupyter Notebooks. I haven't changed anything but now the widget also won't work in Jupyter.

**Comment by nanaeaubry** [comment]
@Chilean-Chili 
What version of the API are you using? And how are you creating the environment? Usually when this occurs the environment was not correctly created. We recommend following this guide: https://developers.arcgis.com/python/guide/install-and-set-up/
If you have Pro installed this is the best way to go.

**Comment by Chilean-Chili** [comment]
@nanaeaubry 
I am using Python 3.9 and the latest Anaconda Navigator (downloaded and installed yesterday).

I tried installing and creating a new environment by following the instructions in this Youtube video (https://youtu.be/jLn-J3y8A1s?t=264), but that method did not work. 

It was only after I deleted the new environment, and installed it in base(root), did it start functioning. 

I used arcgis-2.0.1-py39_2826.tar.bz2 for the installation, and the command: conda install arcgis-2.0.1-py39_2826.tar.bz2

**Comment by nanaeaubry** [comment]
@Chilean-Chili  
Seeing that the video is 2 years old it is a bit out of date regarding this and not made by ESRI. We highly recommend that you use the setup guide from the developers website ( https://developers.arcgis.com/python/guide/install-and-set-up/ ) 

In addition, you can download samples and guides to test out and see if they work for you.
