### ISSUE TITLE
Dataframe export to FeatureSet -- Attribute Error

### ISSUE THREAD

**Issue by Ardy-EDFRE** [Esri/arcgis-python-api#1391]
**Describe the bug**
When exporting a dataframe to featureset, an error occurs with no exported feature.

**To Reproduce**
```python
FS = df.spatial.to_featureset()
```
error:
```python
Traceback (most recent call last):
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-bf78e35f6b4c>", line 1, in <module>
    parcelsWithStatsSDF.spatial.to_featureset()
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py", line 3161, in to_featureset
    return FeatureSet.from_dataframe(self._data)
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\feature.py", line 899, in from_dataframe
    fs = FeatureSet.from_dict(df.spatial.__feature_set__)
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py", line 2920, in __feature_set__
    date_cols = [col for col in df.columns if df[col].dtype == "datetime64[ns]"]
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py", line 2920, in <listcomp>
    date_cols = [col for col in df.columns if df[col].dtype == "datetime64[ns]"]
  File "C:\Users\Ardeshir.Beheshti\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'
```
**Screenshots**

**Expected behavior**

**Platform (please complete the following information):**
 - OS: Windows
 - Python API Version 2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
@Ardy-EDFRE can you provide a dataset that shows this issue?

**Comment by Ardy-EDFRE** [comment]
[export.csv](https://github.com/Esri/arcgis-python-api/files/10116109/export.csv)

**Comment by achapkowski** [comment]
@Ardy-EDFRE what version of the Python API are you using, I cannot reproduce your issue. 

```
import pandas as pd
from arcgis.gis import GIS
from arcgis.geometry import Geometry
import json

df = pd.read_csv(r"C:\temp\export.csv")
df.SHAPE = df.SHAPE.str.replace("'", "\"").apply(json.loads).apply(Geometry)
df.spatial.set_geometry("SHAPE")
fs = df.spatial.to_featureset()
fs2 = df.convert_dtypes().spatial.to_featureset()
```

**Comment by Ardy-EDFRE** [comment]
Version - 2.0.1
Which version of Python API were you able to successfully run on?

**Comment by Ardy-EDFRE** [comment]
@achapkowski - I applied similar functionality & had no luck still with the same error as above. Please re open this issue because it is not completed or solved.

`parcelsWithStatsDF.SHAPE = parcelsWithStatsSDF.SHAPE.str.replace("'", "\"").apply(json.loads).apply(Geometry)
parcelsWithStatsDF.spatial.set_geometry("SHAPE")
fs = parcelsWithStatsDF.spatial.to_featureset()
fs2 = parcelsWithStatsDF.convert_dtypes().spatial.to_featureset()`
