### ISSUE TITLE
Current ArcPy version is unbuildable from Anaconda distribution

### ISSUE THREAD

**Issue by FeralCatColonist** [Esri/arcgis-python-api#1408]
**Describe the bug**
Utilizing the standard command `conda install -c esri arcpy` in a new, empty, conda environment produces a build error which aborts the installation.

**To Reproduce**
```
conda create -n clean_env
y
conda activate clean_env
conda install -c esri arcpy
y
```
error:
```
ERROR conda.core.link:_execute(740): An error occurred while installing package 'esri::jupyter_contrib_nbextensions-0.5.1-py_24'.
Rolling back transaction: done

LinkError: post-link script failed for package esri::jupyter_contrib_nbextensions-0.5.1-py_24
location of failed script: E:\Anaconda3\envs\clean_env\Scripts\.jupyter_contrib_nbextensions-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "E:\Anaconda3\envs\clean_env\Scripts\jupyter-contrib-nbextension-script.py", line 5, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\jupyter_contrib_nbextensions\application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\jupyter_contrib_nbextensions\install.py", line 12, in <module>
    import latex_envs
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\latex_envs\latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
    from .exporters import *
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "E:\Anaconda3\envs\clean_env\lib\site-packages\nbconvert\exporters\html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (E:\Anaconda3\envs\clean_env\lib\site-packages\jinja2\__init__.py)

return code: 1

()
```
**Screenshots**
![image](https://user-images.githubusercontent.com/12204584/210089253-78f50a07-be5a-4221-9a65-5a748c03d212.png)
![image](https://user-images.githubusercontent.com/12204584/210089187-87fe5174-764a-4f08-b287-f0194234ab1c.png)

**Expected behavior**
The build to complete successfully.

**Platform (please complete the following information):**
 - OS: Windows 11
 - Anaconda 2022.10
 - arcgis-2.0.1-py39_2826
 - arcgispro-3.0-0
 - arcpy-3.0-py39_arcgispro_36056
**Additional context**

**Comment by FeralCatColonist** [comment]
Based on [this Github issue](https://github.com/d2l-ai/d2l-book/issues/46), the recommended fix was to upgrade nbconvert.
My current workaround is to install Python first in the environment, then nbconvert, then arcpy; the build was then successful.
```
conda create -n clean_env python=3.9.11
y
conda activate clean_env
conda install -c anaconda nbconvert
conda install -c esri arcpy
y
```

**Comment by FeralCatColonist** [comment]
As a side note, there does not appear to be a conda-way to add `geopandas` into the same environment as `arcpy`. I understand that the team is not responsible for ensuring arcpy works alongside geopandas but this has not been an issue in any of the previous releases since at least 2.7. The current workaround is to `pip install geopandas` after a conda installation of arcpy.

geopandas -> nbconvert -> arcpy
    runs into an absurd amount of conflicts (time-consuming) and won't build
```
conda create -n clean_env python=3.9.11
conda activate clean_env
conda install -c conda-forge geopandas
conda install -c anaconda nbconvert
conda install -c esri arcpy
```
    
nbconvert -> arcpy -> geopandas
    will build, but then there's an error with pyproj imports, (this was also an issue with the first 3.0 release of arcpy)
    once you upgrade pyproj, those errors are resolved but then the environment won't recognize that numpy is installed
    even after removing geopandas, the environment continues to not recognize the installation of numpy
```
conda create -n clean_env python=3.9.11
conda activate clean_env
conda install -c anaconda nbconvert
conda install -c esri arcpy
conda install -c conda-forge geopandas
conda update pyproj
```

**Comment by nanaeaubry** [comment]
@jtroe Do you have any insight on this?

**Comment by nanaeaubry** [comment]
@scw Can you provide some insight for this?

**Comment by nanaeaubry** [comment]
@FeralCatColonist Is this something we should still be aware of or has it been resolved?

**Comment by FeralCatColonist** [comment]
@nanaeaubry it doesn't look it is affecting the current version in 3.1; I've built environments with `install -c esri arcpy` without any issues for the past few months.

**Comment by nanaeaubry** [comment]
@FeralCatColonist Ok glad to hear, sorry you didn't get much help on this post earlier.

I am going to close the issue but feel free to re-open if necessary at any point
