### ISSUE TITLE
Cannot use Jupyter notebooks with arcgis installed using Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/arcgis-python-api#1422]
**Describe the bug**
Whenever I try to install arcgis using conda the arcgis module seems to load the wrong "jupyter notebook" modules targeting **_Windows instead of linux_**. 

**To Reproduce**
1. Create a new environment

```bash
conda create -n smoke -c esri arcgis python=3.9
```

2. open the Jupyter notebook environment
```
jupyter notebook
```
3. create a new notebook using the browser

**Kernel error:**

```python
Traceback (most recent call last):
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/notebook/services/sessions/handlers.py", line 74, in post
    model = yield maybe_future(
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/jupyter_client/multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/jupyter_client/manager.py", line 341, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/jupyter_client/manager.py", line 249, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/site-packages/jupyter_client/launcher.py", line 132, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/mnt/data/miniconda3/envs/smoke/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/miniconda3/envs/smoke\\python.exe'
```
**Screenshots**
![image](https://user-images.githubusercontent.com/921231/211166089-8dd75ca8-12e9-43ed-b625-b5c52b4b8a45.png)

**Expected behavior**
The Jupyter notebook runs like expected.

**Platform (please complete the following information):**
 - OS: Ubuntu LTS 22.04
 - Python API Version 1.8, 1.9, 2.0

**Additional context**
Current workaround is installing the notebook package before arcgis. It seems like the esri channel is using the wrong arch-type.
The kernel.json refers to a Windows python.exe. Changing the path forces a bunch of other OS dependent errors like import error pexpect...

### Workaround:
```bash
conda create -n smoke notebook python=3.9
conda activate smoke
conda install -c esri arcgis
```
Installs the correct arch-type:
```
notebook           pkgs/main/linux-64::notebook-6.5.2-py39h06a4308_0
```
When installing using the esri channel:
```
notebook           esri/noarch::notebook-6.4.12-py_0
```

**Comment by scdub** [comment]
@gisfromscratch I believe I've identified the issue and uploaded package updates which should address it. Could you create a new environment and confirm that it works as expected? Note that since your issue was logged, the API 2.1.0 has been released so that will be used by default unless you explicitly choose another version in your `create` step. The system for generating kernels in Jupyter relies on hardcoded paths, which conda tries to fix to remove, but in this case that path fixing in `ipykernel` wasn't working correctly.

**Comment by gisfromscratch** [comment]
Thanks, that made it. I successfully tested version 2.0 and 2.1 with the notebook package from the esri channel.
