### ISSUE TITLE
add item comment - Too many Failures. Please try again later

### ISSUE THREAD

**Issue by afhughes** [Esri/arcgis-python-api#1481]
**Describe the bug**
I have a notebook on notebook server which adds comments to items in an ArcGIS Enterprise Portal (10.9.1). The error seems to occur when run on many items, it rarely occurs when running on a selection of items (e.g. owned by one user as opposed to whole portal). It does not seem to only occur on particular content types but in general and on common content types such as feature layers

**To Reproduce**
```python
def getMetadataItems():
    results = []
    query_string = "*"    
  
    for s in gis.content.search(query = query_string, max_items =-1):
        
        if s.id in (notification_ids): 

            try:
                tagslist = s.tags
                strtag = ', '.join(tagslist)
                print(s.title) 
                print(s.type)
                print(s.tags)
                print(s.scoreCompleteness)

                # First Warning Append initial tag and comments if metadata score completeness below 80%
                if s.scoreCompleteness < 80 and 'Metadata Requires Updating' not in tagslist and 'Metadata Still Requires Updating' not in tagslist and 'Metadata Intervention Required' not in tagslist:
                    print('First Warning Issued...')
                    newstrtag = strtag + ', Metadata Requires Updating'
                    s.update(item_properties={'tags':newstrtag})
                    s.add_comment('While your item is shared to the organisation it must have metadata complete and up to date. This document will provide more info on how to do this. https://highways.sharepoint.com/:w:/r/sites/DigitalLabSpatial178/_layouts/15/doc2.aspx?sourcedoc=%7BBA5BCA94-C0E2-4267-936D-5BFEE61E64B5%7D')
                # Second Warning. Update tag and add comments if metadata score completeness remains below 80%
                elif s.scoreCompleteness < 80 and 'Metadata Requires Updating' in tagslist:
                    print('Second Warning Issued...')
                    originaltag = tagslist.remove('Metadata Requires Updating')
                    originalstrtag = ', '.join(tagslist)
                    secnewstrtag = originalstrtag + ', Metadata Still Requires Updating'
                    s.update(item_properties={'tags':secnewstrtag})
                    s.add_comment('Metadata Still Requires Updating. Please do this as a matter of urgency.')
                # Third Warning Update tag and add comments and copy info to interventions table if metadata score completeness remains below 80%
                elif 'Metadata Still Requires Updating' in tagslist:
                    print('Copy to intervention table...')
                    originaltag = tagslist.remove('Metadata Still Requires Updating')
                    originalstrtag = ', '.join(tagslist)
                    thrnewstrtag = originalstrtag + ', Metadata Intervention Required'
                    s.add_comment('Please fill out your metadata, this is really important so that users of the Spatial Portal can understand what your item should be used for.')
                    s.update(item_properties={'tags':thrnewstrtag})
                    dict = {"attributes":
                                {
                                    "username": s.owner,
                                    "id": s.id,
                                    "itemtitle": s.title,
                                    "itemurl": s.url
                                }
                            }
                    results.append(dict)

                # If metadata score completenes remains below 80% after warnings info will need to be recopied to interventions table     
                elif s.scoreCompleteness < 80 and 'Metadata Intervention Required'in tagslist:        

                    print('Recopy to intervention table...')       
                    dict = {"attributes":
                                {
                                    "username": s.owner,
                                    "id": s.id,
                                    "itemtitle": s.title,
                                    "itemurl": s.url
                                }
                            }
                    results.append(dict)

                # If metadata if completed then remove tags and add comment
                elif s.scoreCompleteness >= 80 and 'Metadata Intervention Required' in tagslist:
                         print('Metadata now completed...')
                         originaltag = tagslist.remove('Metadata Intervention Required')            
                         s.update(item_properties={'tags':originaltag})                     
                         s.add_comment('Metadata complete')
            except Exception:
                traceback.print_exc()
        
    print (results)        
    return results
```
error:
```python
Traceback (most recent call last):
  File "/tmp/ipykernel_1220/3568381222.py", line 56, in getMetadataItems
    s.add_comment('Please fill out your metadata, this is really important so that users of the Spatial Portal can understand what your item should be used for.')
  File "/opt/conda/lib/python3.7/site-packages/arcgis/gis/__init__.py", line 13164, in add_comment
    res = self._portal.con.post(url, params)
  File "/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1079, in post
    force_bytes=kwargs.pop("force_bytes", False),
  File "/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py", line 625, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py", line 648, in _handle_json_error
    raise Exception(errormessage)
Exception: Too many failures. Please try again later.
(Error Code: 400)
```
**Screenshots**

**Expected behavior**
A comment should be added to the item which triggers an email, code seems to fail on add_comment

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Python API Version 

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
@afhughes This isn't a python api issue, rather an **ArcGIS Enterprise REST API** issue on the `addComment` REST endpoint: https://developers.arcgis.com/rest/users-groups-and-items/add-comment.htm

I strongly suggest you open a support case about this issue.  I will forward it on my end as well.

You can reproduce the issue from the web browser by doing the following:

1. Navigate to any item on ArcGIS Enterprise
2. Open web developer tools in chrome or whatever browser you are using
3. Enter in your message: ```While your item is shared to the organization it must have metadata complete and up to date. This document will provide more info on how to do this. https://highways.sharepoint.com/:w:/r/sites/DigitalLabSpatial178/_layouts/15/doc2.aspx?sourcedoc=%7BBA5BCA94-C0E2-4267-936D-5BFEE61E64B5%7D``` into the comments box.
4. immediately add a second comment of any length from the web browser
5. Notice you get the following message for a message of this length: {"error":{"code":400,"messageCode":"COM_1055","message":"Too many failures. Please try again later.","details":[]}}


Thank you for reporting this.
