### ISSUE TITLE
Error Train Deep Learning Model

### ISSUE THREAD

**Issue by AndreSea26** [Esri/arcgis-python-api#1505]
I am using ArcGIS Pro to run a geoprocessing for Classify mangroves with deep learning. But I am getting this error:

 _Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 297, in <module>
    execute()
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 271, in execute
    callbacks=[ProgressCallback(training_model_object, model_type, max_epochs, out_folder)]
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 739, in fit
    lr = self.lr_find(allow_plot=False)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 574, in lr_find
    raise e
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 571, in lr_find
    self.learn.lr_find()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\fastai\train.py", line 40, in lr_find
    epochs = int(np.ceil(num_it/len(learn.data.train_dl)))
ZeroDivisionError: division by zero_

I am using ArcGIS Pro 2.8.2.
Please let me know if someone knows how to make running this geoprocessing.
![Mangrove error](https://user-images.githubusercontent.com/128828631/227570818-3fb08f46-b993-4cea-be30-5eb04e9afc74.JPG)

**Comment by priyankatuteja** [comment]
@AndreSea26 The api is tool old. I would suggest upgrading the version to Pro 3.0. As a workaround, you could decrease batch size and see if it works.

**Comment by priyankatuteja** [comment]
https://learn.arcgis.com/en/projects/classify-mangroves-using-deep-learning/ guide available with detailed steps

**Comment by priyankatuteja** [comment]
@AndreSea26 Please feel free to open the issue if you face the issue again
