### ISSUE TITLE
Installation issue with new pip version

### ISSUE THREAD

**Issue by aiwalter** [Esri/arcgis-python-api#1608]
**Describe the bug**
Hi team, there is an installation issue with new pip version

**To Reproduce**
```
pip install --upgrade pip  # using pip==23.2
pip install arcgis
```
error:
```
Python interpreter will be restarted.
Looking in indexes: https://pypi.org/simple, https://****@pkgs.dev.azure.com/basf4AP/AP_SGI/_packaging/SGI_Model_Feed/pypi/simple/, https://****@pkgs.dev.azure.com/basf4AP/AP_SGI/_packaging/SGI_Utils_Feed/pypi/simple/
Collecting arcgis
  Downloading https://pkgs.dev.azure.com/basf4AP/e586f807-2260-4726-a2ed-fe9ab8840acb/_packaging/f8ec8436-0149-4010-85cb-9132506a4578/pypi/download/arcgis/2.1.0.3/arcgis-2.1.0.3.tar.gz (44.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 MB 12.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pillow in /databricks/python3/lib/python3.8/site-packages (from arcgis) (8.2.0)
Requirement already satisfied: urllib3 in /databricks/python3/lib/python3.8/site-packages (from arcgis) (1.25.11)
Collecting gssapi (from arcgis)
  Downloading https://pkgs.dev.azure.com/basf4AP/e586f807-2260-4726-a2ed-fe9ab8840acb/_packaging/f8ec8436-0149-4010-85cb-9132506a4578/pypi/download/gssapi/1.8.2/gssapi-1.8.2.tar.gz (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.3/94.3 kB 2.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /bin/sh: 1: krb5-config: not found
      Traceback (most recent call last):
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-643bd3d6-225d-4012-9e04-5021e8d0a843/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-643bd3d6-225d-4012-9e04-5021e8d0a843/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-643bd3d6-225d-4012-9e04-5021e8d0a843/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 130, in _get_build_requires
          self.run_setup()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 109, in <module>
          link_args = shlex.split(get_output(f"{kc} --libs gssapi"))
        File "setup.py", line 22, in get_output
          res = subprocess.check_output(*args, shell=True, **kwargs)
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
**Platform (please complete the following information):**
 - OS: Unix
 - Python: 3.8.10
 - Python API Version: latest

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by aiwalter** [comment]
on Python 3.10 (and on Windows) I get this.

```
Collecting arcgis
  Using cached arcgis-2.0.0.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
     
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
     
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
     
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
     
      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
     
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
     
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Exception encountered when attempting to install: Setting `setup_requires` arg to `[]` and trying again. Exception:
      -----
      Traceback (most recent call last):
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
          keyring >=19,<=21.8.*
                  ~~~~~~~~~~~^
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "C:\Users\X\AppData\Local\Temp\pip-install-fp52879d\arcgis_9731f566a0014a49922a037b2cbc4ab0\setup.py", line 348, in <module>
          setup(**kwargs)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\__init__.py", line 106, in setup 
          _install_setup_requires(attrs)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\setuptools\installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\__init__.py", line 804, in resolve
          requirements = list(requirements)[::-1]
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\__init__.py", line 3173, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "C:\Users\X\Miniconda3\envs\env310\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          keyring >=19,<=21.8.*
                  ~~~~~~~~~~~^
      error in arcgis setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          keyring >=19,<=21.8.*
                  ~~~~~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jpmeijers** [comment]
This problem isn't really solved until that release is made. Currently I am stuck with v1.9.1 of the python library, because v2.0.0 is the only one allowed to be installed by pip on python >=v3.10, but fails. And I need to use Python >=v3.10 otherwise I run into OpenSSL and urllib3 problems.

What is the recommended combinations of versions to currently use?

**Comment by nanaeaubry** [comment]
We only support up to (and including) python 3.9 until now. At version 2.2.0 there will be support for 3.9, 3.10, and 3.11.


Currently you can use 'python v3.9' with 'openssl v3 'and 'urllib3 v1'

Hope that helps. We do have a pre-release of 2.2.0 out that you can use: `conda install -c "esri/label/prerelease" arcgis`
