### ISSUE TITLE
spatial.to_featureclass() errors on spatial reference

### ISSUE THREAD

**Issue by BruceHarold** [Esri/arcgis-python-api#1745]
**Describe the bug**
When I use spatial.to_featureclass() I get an ArcPy error, to_featureset() works.

**To Reproduce**
See the attached Notebook

**Error in Pro or Notebook**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bruc5588\AppData\Local\ESRI\conda\envs\arcgispro-py3-quack\lib\site-packages\arcgis\features\geo\_accessor.py", line 2668, in to_featureclass
    result = to_featureclass(
  File "C:\Users\bruc5588\AppData\Local\ESRI\conda\envs\arcgispro-py3-quack\lib\site-packages\arcgis\features\geo\_io\fileops.py", line 1262, in to_featureclass
    raise e
  File "C:\Users\bruc5588\AppData\Local\ESRI\conda\envs\arcgispro-py3-quack\lib\site-packages\arcgis\features\geo\_io\fileops.py", line 1095, in to_featureclass
[VirtualizeCSV.zip](https://github.com/Esri/arcgis-python-api/files/14030074/VirtualizeCSV.zip)

    fc = arcpy.CreateFeatureclass_management(
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 3541, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 3538, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spatial_grid_3, out_alias, oid_type), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000622: Failed to execute (Create Feature Class). Parameters are not valid.
 ERROR 000614: Cannot create Spatial Reference for spatial_reference

**Expected behavior**
A feature class should be written

**Platform (please complete the following information):**
 - OS: Windows 10 Enterprisee
 - Browser Chrome
 - Python API Version 2.2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
Please try with 2.4.0, this has been addressed

**Comment by BruceHarold** [comment]
@nanaeaubry Just tried it in 2.4.0 - worked perfectly - thanks!
