### ISSUE TITLE
Empty 'name' property of an arcgis item object causes crash when trying to clone

### ISSUE THREAD

**Issue by Miralupa** [Esri/arcgis-python-api#1872]
**Describe the bug**
An item with an empty name will cause a crash if this item is cloned.

**To Reproduce**
No particular piece of code, just a simple call to '_clone_items_' will trigger the crash when an item has an empty name.

```python
agol.content.clone_items(items=[itemWithEmptyName])
```

Here is my workflow that lead me to this problem : I share some items of my portal through a collaboration towards ArcGIS Online. Then, once in ArcGIS Online, I try to clone the recently appeared items using the arcgis Python API. However, a crash occurs during the '_clone_items_' function call of the arcgis Python API. The empty '_name_' property of the item is the cause of the crash. In my portal source item, the _item.name_ is None (not on all of my items, but on some of them. I don't know if it is normal or if it is legacy after upgrading my arcgis enterprise). Once such item is created in ArcGIS Online through collaboration, the _name_ property is not None anymore, but it became an empty string ''. And this empty string is the cause of the crash during the clone_items step of my workflow.

error:
in arcgis Python 2.3.0

> Traceback (most recent call last):
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\_impl\common\_clone.py", line 2945, in clone
>     name = self._get_unique_name(self.target, name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\_impl\common\_clone.py", line 2850, in _get_unique_name
>     if name[0].isdigit():
>        ~~~~^^^
> IndexError: string index out of range

**Expected behavior**
In my opinion, 2 or maybe 3 problems occur during this workflow :

1. I don't know if the '_name_' property of an item should be None or empty in the first place. I don't know how this property is forged and what are its purprose and usages (equals to '_title_' most of the case), so maybe this isn't a real problem. But just for you to know : it can happen in production.
2. the collaboration between my portal and ArcGIS Online doesn't recreate the item identically, as a None _item.name_ becomes an empty string. I would expect an None property to remain None after collaboration. Maybe this problem should be forwarded to another dev team that works on collaboration.
3. And empty name causes the crash in the python _clone_items_ call. It is due to the following piece of code line 2941 of the _clone.py script of the arcgis Python module:

```python
name = original_item["name"]
if name is None:
    name = os.path.basename(os.path.dirname(original_item["url"]))

name = re.sub("\W+", "_", name)
name = self._get_unique_name(self.target, name)
```

The test '_if name is None_' might not be robust enough and should treat the empty string too (or do something else accordingly) before the 'self._get_unique_name' call in which the 'name[0]' crashes.

**Platform:**
 - OS: Windows (irrelevant to the problem)
 - Browser : Chrome (irrelevant to the problem)
 - Python API Version : crash reproduced in 1.8.5 and in 2.3.0
 - ArcGIS Enterprise : 10.91

**Additional context**
Original problem opened [there](https://community.esri.com/t5/arcgis-api-for-python-questions/name-property-in-python-arcgis-gis-item-object/m-p/1497593), a colleague of yours pointed me here.

**Comment by nanaeaubry** [comment]
This has been fixed for the next release, thanks!
