### ISSUE TITLE
Failed to upload the local experience when set the parameter "auto_remap=True"

### ISSUE THREAD

**Issue by fz0000** [Esri/arcgis-python-api#1884]
**Describe the bug**
When I want to upload a local exp with `auto_remap=True`, Error occurs.

**To Reproduce**
Run the script to upload a local experience:
```python
from arcgis.apps.expbuilder import WebExperience
from arcgis.gis import GIS

my_gis = GIS('https://myserver.mydomain.com/portal', 'admin', 'password')
my_exp = WebExperience(gis=my_gis, path='/path/to/config.json')
new_item = my_exp.upload(gis=my_gis, auto_remap=True)
```
error:
```python
Traceback (most recent call last):
  File "/path/to/myscript.py", line 6, in <module>
    new_item = my_exp.upload(gis=my_gis, auto_remap=True)
  File "/venv_path/to/site-packages/arcgis/apps/expbuilder/expbuilder.py", line 787, in upload
    test_gis = GIS(url=url)
               ^^^
NameError: name 'GIS' is not defined. Did you mean: 'gis'?
```
Then I found that the 13th line of the `expbuilder.py` is commented out. Was it accidental?
```python
# from arcgis.gis import GIS
```

**Platform (please complete the following information):**
 - OS: [Windows 11]
 - Browser [N/A]
 - Python API Version [2.3.1]

**Comment by nanaeaubry** [comment]
@fz0000 Thanks for catching that! We put a fix for the next release
