### ISSUE TITLE
Can't fetch popup of layers within a `GroupLayer`

### ISSUE THREAD

**Issue by ccone-pattern** [Esri/arcgis-python-api#2108]
**Describe the bug**
When fetching the popup of a layer nested within a `GroupLayer`, an attribute error is raised claiming that a non-public variable `_layers` does not exist

**To Reproduce**
```python
layers = LayerFormHandler.fetch_items(cfg.layer_ids) # returns list of Items
wm = MapHandler.upsert(layers) # creates/updates Map given list of Items

for iL, lyr in enumerate(wm.content.layers):
        
    if isinstance(lyr, GroupLayer):
        gl = lyr
        lyr = lyr.layers[0]
    else:
        gl = None
           
    field_infos = []
    for field in lyr.properties.fields:
        if field["name"] != "GlobalID" and not field.get("domain"):
            field_infos.append(
                FieldInfo(fieldName=field["name"], isEditable=True, label=field["alias"], visible=True)
                )
    if gl:
        gl.popup(0).edit(popup_elements=[PopupElementFields(fieldInfos=field_infos, type="fields")])

error:
```python
Traceback (most recent call last):
  File "C:\Users\Charlie.Cone\repos\Field Maps Deployment Tool\deploy_field_maps\main.py", line 74, in <module>
    field_map = main()
                ^^^^^^
  File "C:\Users\Charlie.Cone\repos\Field Maps Deployment Tool\deploy_field_maps\main.py", line 52, in main
    gl.popup(0).edit(popup_elements=[PopupElementFields(fieldInfos=field_infos, type="fields")])
    ^^^^^^^^^^^
  File "C:\Users\Charlie.Cone\AppData\Local\anaconda3\envs\esri-source\Lib\site-packages\arcgis\map\group_layer.py", line 124, in popup
    is_table = isinstance(self._layers.layers[index], self._spec.Table)
                          ^^^^^^^^^^^^
AttributeError: 'GroupLayer' object has no attribute '_layers'. Did you mean: '_layer'?
```
**Screenshots**

**Expected behavior**
Fetch popup from indexed `FeatureLayer` within `GroupLayer` - [as specified in the docs ](https://developers.arcgis.com/python/latest/api-reference/arcgis.map.toc.html#arcgis.map.map_widget.MapContent.popup)for the `MapContent.popup` method.

**Platform (please complete the following information):**
 - OS: Windows 64x
 - Browser Edge
 - Python API Version 2.4.0

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@ccone-pattern That is an unfortunate bug on our end. Sorry about this we will fix it but not sure when we can get a patch out, I will put a comment here when we know

**Comment by nanaeaubry** [comment]
@ccone-pattern We do not want users creating the PopupManager themselves but you can use this to get the PopupManager for your layer inside the group layer until the fix is released:

```
gl = webmap.content.layers[0] # group layer in map
PopupManager(
            gl._layer.layers[index], source=gl, spec=gl._spec, is_table=False
        )
```

`index` is the index of the layer inside the group layer

**Comment by nanaeaubry** [comment]
Closing since fixed for the next release
