### ISSUE TITLE
BasemapManager move_from_basemap() not working.

### ISSUE THREAD

**Issue by Clubdebambos** [Esri/arcgis-python-api#2177]
**Describe the bug**
The move_from_basemap() method from the BasemapManager should accept an index and remove that layer from the baseMapLayers, however, I keep getting an AttributeError: 'NoneType' object has no attribute 'dict'. My WebMap is using the gray-vector basemap. Attempted with multiple WebMaps with various basemaps and the result is the same issue.

The [documentation ](https://developers.arcgis.com/python/latest/api-reference/arcgis.map.toc.html#arcgis.map.map_widget.BasemapManager.move_from_basemap)has an example which is not correct either.

**To Reproduce**
```python
from arcgis.gis import GIS
from arcgis.map import Map

"""Access AGOL"""
agol = GIS("home")

wm_item = agol.content.get("WM_ITEM_ID")

webmap = Map(wm_item)

"""Move from Basemap"""
webmap.basemap.move_from_basemap(0)

"""Update the Map Object"""
status = webmap.update()
print(status)

```
error:
```python
Traceback (most recent call last):
  File "<module4>", line 12, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\map\map_widget.py", line 1542, in move_from_basemap
    self._helper.move_from_basemap(index)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\map\_utils.py", line 1628, in move_from_basemap
    raise e
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\map\_utils.py", line 1620, in move_from_basemap
    self._check_basemap_sr(self.pydantic_class.base_map.base_map_layers[0])
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\map\_utils.py", line 540, in _check_basemap_sr
    layer_sr = self._get_service_spatial_reference(service)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\map\_utils.py", line 577, in _get_service_spatial_reference
    (service.full_extent.dict().get("spatialReference", {}).get("wkid"))
     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dict'
```
**Screenshots**

**Expected behavior**
Expecting the script to complete and the basemap layer from the selected index used in the move_to_layer() method to be moved from the basemap to the operationalLayers.

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Python API Version 2.4.0

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@Clubdebambos Will take a look thanks for reporting

**Comment by nanaeaubry** [comment]
Fixed for the next release thanks!
