### ISSUE TITLE
PyProj 2.0.x may not be compatible anymore

### ISSUE THREAD

**Issue by phillip-martin** [Esri/arcgis-python-api#339]
I came across a small speedbump when attempting to publish a new feature layer, and I couldn't find this problem  in any of the other issues.

I'm using `arcgis==1.5.2` - `pip install arcgis` installed all other dependencies.

When calling`lyr=sdf.spatial.to_featurelayer('spatialai_CA_demo_segments_q2_2018')`
I received an error:
```
Traceback (most recent call last):
  File "publish.py", line 124, in <module>
    main()
  File "publish.py", line 104, in main
    lyr = sdf.spatial.to_featurelayer('spatialai_CA_demo_segments_q2_2018')
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/arcgis/features/geo/_accessor.py", line 1843, in to_featurelayer
    return content.import_data(self._data, title=title, tags=tags)
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/arcgis/gis/__init__.py", line 3672, in import_data
    name)
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/arcgis/features/geo/_accessor.py", line 1791, in to_featureclass
    overwrite=overwrite)
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/arcgis/features/geo/_io/fileops.py", line 555, in to_featureclass
    out_name=fc_name)
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/arcgis/features/geo/_io/fileops.py", line 594, in _pyshp_to_shapefile
    shpfile = shapefile.Writer(GEOMTYPELOOKUP[geom_type])
  File "/home/phillip/work/esri/env3/lib/python3.6/site-packages/shapefile.py", line 1017, in __init__
    self.shp = self.__getFileObj(os.path.splitext(target)[0] + '.shp')
  File "/home/phillip/work/esri/env3/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not in
```

The crucial spot is line 594 on in arcgis/features/geo/_io/fileops.py
```
shpfile = shapefile.Writer(GEOMTYPELOOKUP[geom_type])
```

Seems that in [pyshp](https://github.com/GeospatialPython/pyshp)'s 2.0.0 update (Early November 2018), they modified their api heavily and now disallow using the geometry type parameter as the first argument of `shapeifle.Writer()`.

The simple fix for me was to downgrade pyshp to 1.2.12.

Not a huge impediment to my progress, so it all worked out, but it took me a bit by surprise that the setup installed an incompatible dependency.

I hope this was helpful.

**Comment by phillip-martin** [comment]
@DavidJVitale, really happy to see the quick reply. Since there is no reason to use the latest pyshp, I will stay with 1.2.12.

Glad this could be of help.
