### ISSUE TITLE
Creating a Geometry from a Shapely object is not working

### ISSUE THREAD

**Issue by jrmatchett** [Esri/arcgis-python-api#366]
In arcgis version 1.5.3 (and I believe 1.5.1 and 1.5.2), creating a Geometry object from a Shapely object isn't working correctly. For example, in version 1.5.0:
```
>>> from arcgis.geometry import Geometry
>>> from shapely.geometry import Point as ShapelyPoint
>>> pt = ShapelyPoint(37.1, -117.3)
>>> Geometry(pt.__geo_interface__)
{'x': 37.1, 'y': -117.3, 'spatialReference': {'wkid': 4326}}
```
However, in version 1.5.3 this is the result:
```
>>> Geometry(pt.__geo_interface__)
{'type': 'Point', 'coordinates': (37.1, -117.3)}
```
This creates issues for certain Geometry methods (such as `buffer`) that require a geometry to be converted to a Shapely geometry when the ArcPy geometry engine isn't available. For example:
```
>>> pt2 = Geometry({'x':37.1, 'y':-117.3, 'spatialReference': {'wkid':4326}})
>>> pt2_buff = pt2.buffer(10)
>>> pt2_buff.area
Traceback (most recent call last):
  File "/Users/me/anaconda3/envs/arcgis153/lib/python3.7/site-packages/arcgis/geometry/_types.py", line 144, in __getattr__
    return dict.__getitem__(self, name)
KeyError: 'area'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/anaconda3/envs/arcgis153/lib/python3.7/site-packages/arcgis/geometry/_types.py", line 146, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, name))
AttributeError: 'Geometry' object has no attribute 'area'
```

**Comment by achapkowski** [comment]
@jrmatchett the issue has already been addressed and will be fixed in the next released.
Thank you for reporting this.
