### ISSUE TITLE
item.shared_with permissions issue

### ISSUE THREAD

**Issue by DanCranford** [Esri/arcgis-python-api#579]
There's an issue with the .shared_with property of an item object.  On certain items I'm accessing as an admin, I'm being told "You do not have permissions to access this resource or perform this operation."  I have tested the following:

- I'm able to access group information for groups within my org

- I'm able to access group information for groups in other orgs that I'm a member of

- The items that I'm experiencing this issue on are marked as a "Favorite" item for another user (potentially in another org).

**To Reproduce**
Do the following on an item that has been marked as a "favorite" by someone else.
```python
item.shared_with
```
error:
```python
You do not have permissions to access this resource or perform this operation.

Traceback (most recent call last):

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\IPython\core\formatters.py", line 224, in catch_format_error

    r = method(self, *args, **kwargs)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\IPython\core\formatters.py", line 702, in __call__

    printer.pretty(obj)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\IPython\lib\pretty.py", line 400, in pretty

    return _repr_pprint(obj, self, cycle)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\IPython\lib\pretty.py", line 695, in _repr_pprint

    output = repr(obj)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\gis\__init__.py", line 5130, in __repr__

    return '<%s title:"%s" owner:%s>' % (type(self).__name__, self.title, self.owner)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\gis\__init__.py", line 5108, in __getattr__

    self._hydrate()

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\gis\__init__.py", line 5101, in _hydrate

    groupdict = self._portal.get_group(self.groupid)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\_impl\portalpy.py", line 900, in get_group

    return self.con.post('community/groups/' + group_id, self._postdata())

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\_impl\connection.py", line 1183, in post

    self._handle_json_error(resp_json['error'], errorcode)

  File "C:\Users\me\AppData\Local\ESRI\conda\envs\newenv\lib\site-packages\arcgis\_impl\connection.py", line 1204, in _handle_json_error

    raise RuntimeError(errormessage)

RuntimeError: You do not have permissions to access this resource or perform this operation.

(Error Code: 403)
```

I would hope that this could be fixed to ignore or pass on the groups that the user doesn't have access to.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Python API Version: 1.7.0

**Comment by timhaverland-noaa** [comment]
I'm also seeing this in version 1.6.1.

**Comment by CMPeng** [comment]
When in version 1.7.1, 
if accessed via credentials of the user who `favorites` the item,
`a_item.shared_with` returns 
```
{'everyone': True,
 'org': True,
 'groups': [<Group title:"Favorites - Demo Account" owner:arcgis_python>]}
```
if accessed via credentials of the admin who owns the org of the previous user, then
`b_item.shared_with` returns 
`{'everyone': True, 'org': True, 'groups': []}`

if accessed via credentials of the admin of a different org, then
`c_item.shared_with` returns 
`{'everyone': True, 'org': True, 'groups': []}`
* * *
Compared to what's logged here for 1.6 series, that -
if accessed via credentials of the admin who owns the org of the previous user, then
`b_item.shared_with` returns 
```
{'everyone': True,
 'org': True,
 'groups': [<Group title:"Favorites - Demo Account" owner:arcgis_python>]}
```

if accessed via credentials of the admin of a different org, then
`c_item.shared_with` returns 
Exception (as mentioned in the issue itself)
* * *
There seem to be 2 issues - (1) for cases b and c (admin of this org, and admin of a diff org), the token is not appended at the REST call for </sharing/rest/content/items/xxx/groups>, (is it a regression from 1.6 to 1.7) and (2) shall we make the enhancement to let the exception not float to the top but instead give a warning (as stated in the issue itself)?

@achapkowski Can you please shed some lights in here? Thanks!

**Comment by achapkowski** [comment]
This issue should be addressed in the next release.  Thank you for reporting.

**Comment by daraobeirne** [comment]
FYI I'm also seeing this behavior when I try accessing the the item.homepage object https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html?highlight=homepage#arcgis.gis.Item.homepage
