### ISSUE TITLE
ArcGIS API 1.8 SAML App Log In Crash on self._me()  Against AGOL _portalpy.py get_user(self, username)

### ISSUE THREAD

**Issue by Hlindemann** [Esri/arcgis-python-api#630]
**Describe the bug**
When Trying to Login with App ID api crashes when SAML is configured

**To Reproduce**
```python
from arcgis.gis import GIS
import requests
import logging
import getpass

logging.basicConfig(level=logging.DEBUG)
gis_ = GIS('https://somename.maps.arcgis.com', client_id='vAAAAAAAAAAn')
print("Successfully logged in as: " + gis_.properties.user.username)
_users = gis_.users.search()
for user in _users:
    print(user)
```
error:
```python
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/Code/Python3/EsriProduction/arcgis_api_1_8/arcgis_api.py", line 8, in <module>
    gis_ = GIS('https://somename.maps.arcgis.com/', client_id='vAAAAAAAn')
  File "E:\Code\Python3\EsriProduction\arcgis_api_1_8\venv\lib\site-packages\arcgis\gis\__init__.py", line 384, in __init__
    me = self.users.me
  File "E:\Code\Python3\EsriProduction\arcgis_api_1_8\venv\lib\site-packages\arcgis\gis\__init__.py", line 2775, in me
    self._me = User(self._gis, meuser['username'], meuser)
TypeError: string indices must be integers
```
**Screenshots**
![image](https://user-images.githubusercontent.com/21313366/76289269-65826800-62b1-11ea-994a-322515e13c9d.png)

![image](https://user-images.githubusercontent.com/21313366/76289294-7337ed80-62b1-11ea-8328-d7ced482bf0d.png)

**Expected behavior**
Valid Login

**Platform (please complete the following information):**
 - OS: N\A
 - Browser : N\A
 - Python API Version: 1.8.0

**Additional context**
When Using this workflow the method returns a path to a file containing the JSON not json or None
```python
    def get_user(self, username):
        """ Returns the user information for the specified username.

        Arguments
            username        required string, the username whose information you want.

        :return:
            None if the user is not found and returns a dictionary object if the user is found
            the dictionary has the following keys:

            ================  ========================================================
            **Key**           **Value**
            ----------------  --------------------------------------------------------
            access            string
            ----------------  --------------------------------------------------------
            created           time (int)
            ----------------  --------------------------------------------------------
            culture           string, two-letter language code ('en')
            ----------------  --------------------------------------------------------
            description       string
            ----------------  --------------------------------------------------------
            email             string
            ----------------  --------------------------------------------------------
            fullName          string
            ----------------  --------------------------------------------------------
            idpUsername       string, name of the user in the enterprise system
            ----------------  --------------------------------------------------------
            groups            list of dictionaries.  For dictionary keys, see get_group doc.
            ----------------  --------------------------------------------------------
            modified          time (int)
            ----------------  --------------------------------------------------------
            orgId             string, the organization id
            ----------------  --------------------------------------------------------
            preferredView     string, value is either Web, GIS, or null
            ----------------  --------------------------------------------------------
            region            string, None or two letter country code
            ----------------  --------------------------------------------------------
            role              string, value is either org_user, org_publisher, org_admin
            ----------------  --------------------------------------------------------
            storageUsage      int
            ----------------  --------------------------------------------------------
            storageQuota      int
            ----------------  --------------------------------------------------------
            tags              list of strings
            ----------------  --------------------------------------------------------
            thumbnail         string, name of file
            ----------------  --------------------------------------------------------
            username          string, name of user
            ================  ========================================================
        """
        result = self.con.post('community/users/' + username, self._postdata())

       #Temp fix
        if os.path.isfile(result) is True:
            with open(result) as f:
                result = json.loads(f.read())
        return result
```

**Comment by achapkowski** [comment]
I'll take a look, thank you for reporting

**Comment by achapkowski** [comment]
@Hlindemann can you answer some questions:

- do your users names have `.` in them?  
- what type of security is your portal?  BUILT-IN? something else?

Thank you

**Comment by Hlindemann** [comment]
Hi Andrew, 
This is using SAML and the Microsoft account it is a Enterprise Login
for that I have to use a token generated by a registered application.

It seems that the users are created by default as below it takes the email and appends the domain
The username format is **username@esri_southafrica.com_esriza** 
**do your users names have . in them?**
       yes

This is against AGOL

![image](https://user-images.githubusercontent.com/21313366/76749176-c06e0080-6784-11ea-985a-7eb79e2db60c.png)

![image](https://user-images.githubusercontent.com/21313366/76748627-c3b4bc80-6783-11ea-8cde-65a5ef53e3c3.png)

![image](https://user-images.githubusercontent.com/21313366/76749242-dda2cf00-6784-11ea-8ee8-f6a708ad1898.png)

**Comment by achapkowski** [comment]
This should be resolved.  Please update to the latest version of the ArcGIS API for Python.

```bash
     conda install -c esri/label/prerelease arcgis
```

**Comment by mquetel** [comment]
@Hlindemann Would it be possible to get sample code that demonstrates the workflow you screen grabbed above, which opens a browser in python and prompts for SAML login?  I've been searching for an example and have failed to find an esri provided one.  Thanks in advance!

**Comment by Hlindemann** [comment]
Hi @mquetel 
so you create a application in AGOL 
![image](https://user-images.githubusercontent.com/21313366/107476617-e1022e80-6b7e-11eb-88bd-2a4e667870bf.png)

Under Settings go to registered info and get the App ID and replace the client_id parameter below with the app id.
```python
from arcgis.gis import GIS
import logging

logging.basicConfig(level=logging.DEBUG)

gis_ = GIS('https://my_org.maps.arcgis.com', client_id='AAAAAAAAAAA')
print("Successfully logged in as: " + gis_.properties.user.username)
_users = gis_.users.search()
for user in _users:
    print(user)
python```
