### ISSUE TITLE
tensorboardX error logging the graph

### ISSUE THREAD

**Issue by chenzhaiyu** [Esri/arcgis-python-api#750]
**Describe the bug**
tensorboardX throws an error writing the graph, when PointCNN starts training.

**To Reproduce**
```python
from arcgis.learn import PointCNN
from arcgis.learn import export_point_dataset
from arcgis.learn import prepare_data

path = r'../../Datasets/dales_las'
output_path = r'data'

export_point_dataset(path, output_path, 50.0, 8192)

colormap = {'0':[220,220,220], '1':[255,0,0], '2':[0,255,0], '3':[0,0,255], '4':[51,204,204], '5':[204,102,255],
            '6':[255,255,102], '7':[255,102,0], '8':[204,0,153]}

data = prepare_data(output_path, dataset_type='PointCloud', batch_size=4, color_mapping=colormap)

pointcnn = PointCNN(data)

pointcnn.fit(epochs=20, tensorboard=True)
```
error:
```python
# if tensorboardX==1.7, as required by https://developers.arcgis.com/python/api-reference/arcgis.learn.html#arcgis.learn.PointCNN.fit
Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\fastai\callbacks\tensorboard.py", line 234, in _queue_processor
    request.write()
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\fastai\callbacks\tensorboard.py", line 424, in write
    self.tbwriter.add_graph(model=self.model, input_to_model=self.input_to_model)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\tensorboardX\writer.py", line 697, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\tensorboardX\pytorch_graph.py", line 288, in graph
    trace, _ = torch.jit.get_trace_graph(model, args)
AttributeError: module 'torch.jit' has no attribute 'get_trace_graph'
```

```python
# elif tensorboardX==1.8/1.9/2.0/2.1
Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\fastai\callbacks\tensorboard.py", line 234, in _queue_processor
    request.write()
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\fastai\callbacks\tensorboard.py", line 424, in write
    self.tbwriter.add_graph(model=self.model, input_to_model=self.input_to_model)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\tensorboardX\writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\tensorboardX\pytorch_graph.py", line 240, in graph
    trace = torch.jit.trace(model, args)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\torch\jit\__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\torch\jit\__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\torch\nn\modules\module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "D:\Softwares\Anaconda\envs\arcgis-api-env\lib\site-packages\torch\nn\modules\module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```
**Screenshots**
N.A.

**Expected behavior**
The graph being written into the training log.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/Pycharm Jupyter notebook extension
 - Python API Version: 1.8.1
 - Pytorch: 1.4
 - fastai: 1.0.60
(Installation followed: https://developers.arcgis.com/python/guide/point-cloud-segmentation-using-pointcnn/#For-ArcGIS-Pro-users:)

**Additional context**
Only the graph writing crashes. Suspected compatibility issue with Pytorch/fastai.

**Comment by priyankatuteja** [comment]
To fix this error, you need to install dependencies required to run PointCNn model. commands for anaconda users

```
conda create -n arcgis-api-env python=3.6.10 
conda activate arcgis-api-env 
conda install -c esri arcgis=1.8.1
conda install -c esri -c fastai -c pytorch scikit-image=0.15.0 pillow=6.2.2 libtiff=4.0.10 fastai=1.0.60 pytorch=1.4.0 torchvision=0.5.0 cudatoolkit=10.1.243 jupyterlab=2.0.1
conda install -c plotly plotly=4.5.4 plotly-orca=1.3.1 psutil=5.7.0 nodejs=10.13 h5py=2.10.0 gdal=2.3.3 tensorflow-gpu=2.1.0
pip install torch-scatter==latest+cu101 torch-sparse==latest+cu101 torch-cluster==latest+cu101 torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
```
