### ISSUE TITLE
FeatureSet.from_geojson Fails on MultiPolygons

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#758]
While responding to a GeoNet thread, [FeatureSet.from_geojson bug?](https://community.esri.com/thread/257817-featuresetfromgeojson-bug), I was able to verify a defect in FeatureSet.from_geojson with MultiPolygon.

 Using a basic MultiPolygon example from [GeoJSON - Wikipedia](https://en.wikipedia.org/wiki/GeoJSON), you can generate an error:
```python
>>> from arcgis.features import FeatureSet
>>>
>>> geojson_multipolygon = {
...   "type": "FeatureCollection",
...   "features": [{
...     "type": "Feature",
...     "geometry" : {
...       "type": "MultiPolygon",
...       "coordinates": [
...         [[[30, 20], [45, 40], [10, 40], [30, 20]]],
...         [[[15, 5], [40, 10], [10, 20], [5, 10], [15, 5]]]
...       ]
...     },
...     "properties": {
...       "name": "Wikipedia MultiPolygon example"
...     }
...   }]
... }
>>>
>>> FeatureSet.from_geojson(geojson_multipolygon)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 922, in from_geojson
    return FeatureSet.from_dict(geo_to_esri(geojson))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 826, in geo_to_esri
    esri["features"] = list(esri_features)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 832, in extract
    geometry = get_geometry(feature)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 880, in get_geometry
    geometry = Geometry(json.loads(geom))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'Polygon'
>>> 
```
Using the polygon with a hole example from [GeoJSON - Wikipedia](https://en.wikipedia.org/wiki/GeoJSON) , the method works fine:
```python
>>> from arcgis.features import FeatureSet
>>> 
>>> geojson_polygon = {
...   "type": "FeatureCollection",
...   "features": [{
...     "type": "Feature",
...     "geometry": {
...       "type": "Polygon",
...       "coordinates": [
...         [[35, 10], [45, 45], [15, 40], [10, 20], [35, 10]],
...         [[20, 30], [35, 35], [30, 20], [20, 30]]
...       ]
...     },
...     "properties": {
...       "name": "Wikipedia Polygon example with hole"
...     }
...   }]
... }
>>>
>>> FeatureSet.from_geojson(geojson_polygon)
<FeatureSet> 1 features
>>> 
```

**Comment by achapkowski** [comment]
I'll take a look. thanks for reporting.

**Comment by achapkowski** [comment]
Is this occurring with or without ArcPy?

**Comment by achapkowski** [comment]
This only happens if ArcPy is not present it seems.

**Comment by bixb0012** [comment]
@achapkowski , I see this with ArcPy from Pro 2.6 installed as well.
```python
>>> from operator import itemgetter
>>> from arcgis.features import FeatureSet
>>>
>>> import arcpy
>>> import arcgis
>>>
>>> itemgetter('ProductName', 'Version', 'BuildNumber')(arcpy.GetInstallInfo())
('ArcGISPro', '2.6', '24783')
>>> arcgis.__version__
'1.8.1'
>>>
>>> geojson_multipolygon = {
...   "type": "FeatureCollection",
...   "features": [{
...     "type": "Feature",
...     "geometry" : {
...       "type": "MultiPolygon",
...       "coordinates": [
...         [[[30, 20], [45, 40], [10, 40], [30, 20]]],
...         [[[15, 5], [40, 10], [10, 20], [5, 10], [15, 5]]]
...       ]
...     },
...     "properties": {
...       "name": "Wikipedia MultiPolygon example"
...     }
...   }]
... }
>>>
>>> FeatureSet.from_geojson(geojson_multipolygon)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 922, in from_geojson
    return FeatureSet.from_dict(geo_to_esri(geojson))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 826, in geo_to_esri
    esri["features"] = list(esri_features)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 832, in extract
    geometry = get_geometry(feature)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py", line 880, in get_geometry
    geometry = Geometry(json.loads(geom))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\json\__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'Polygon'
>>>
```
Esri Support was able to reproduce the defect with ArcPy installed as well, and the following Esri Support bug was logged:
> **#BUG-000133455** FeatureSet.from_geojson Fails when used with MultiPolygons.

**Comment by achapkowski** [comment]
It will be fixed in the next release.  That is why it was closed.
