### ISSUE TITLE
Pip installation fails on travis

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-python-api#807]
**Describe the bug**

Cannot use arcgis package in travis ci

**To Reproduce**

run a travis ci job that imports arcgis

error:
```python
Collecting arcgis==1.8
  Downloading arcgis-1.8.0.tar.gz (1.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python3.6.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ttyv3zw/arcgis/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ttyv3zw/arcgis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b5s7l09z
         cwd: /tmp/pip-install-2ttyv3zw/arcgis/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2ttyv3zw/arcgis/setup.py", line 151, in <module>
        [(_get_rel_site_packages_dir() + "arcgis/gis/_impl", [
      File "/tmp/pip-install-2ttyv3zw/arcgis/setup.py", line 27, in _get_rel_site_packages_dir
        for sitepackages in site.getsitepackages():
    AttributeError: module 'site' has no attribute 'getsitepackages'
```

**Expected behavior**

I expect arcgis to install correctly as it does with pip on osx or windows

**Comment by sandeepgadhwal** [comment]
Related to https://github.com/pypa/virtualenv/issues/737 https://github.com/pypa/pipenv/issues/3824

**Comment by sandeepgadhwal** [comment]
@priyankatuteja @steveoh 

The problem is in the default environment. You can use something like this to create a new virtual environment and run tests

https://github.com/sandeepgadhwal/travis_arcgis_test

**Comment by priyankatuteja** [comment]
@sandeepgadhwal Thanks! @steveoh Please try the steps and let us know if you still face it.
