### ISSUE TITLE
GeoAccessor.from_table Returns OutOfBoundsDatetime Error With Dates Earlier Than 1677

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#833]
Whenever I use `GeoAccessor.from_table` with tables that have fields with dates earlier than 1677, I get the following error:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\geo\_accessor.py", line 2422, in from_table
    return from_table(filename, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\geo\_io\fileops.py", line 257, in from_table
    null_value=null_value))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\frame.py", line 493, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\internals\construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\internals\construction.py", line 83, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\internals\construction.py", line 352, in _homogenize
    val, index, dtype=dtype, copy=False, raise_cast_failure=False
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\construction.py", line 427, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\construction.py", line 553, in _try_cast
    subarr = maybe_cast_to_datetime(arr, dtype)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\dtypes\cast.py", line 1419, in maybe_cast_to_datetime
    value = tslibs.conversion.ensure_datetime64ns(value)
  File "pandas\_libs\tslibs\conversion.pyx", line 246, in pandas._libs.tslibs.conversion.ensure_datetime64ns
  File "pandas\_libs\tslibs\np_datetime.pyx", line 113, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-05-04 00:00:00
``` 
I know it is related to https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html , 
> ## Timestamp limitations
> Since pandas represents timestamps in nanosecond resolution, the time span that can be represented using a 64-bit integer is limited to approximately 584 years:
>```python
> >>> pd.Timestamp.min
> Timestamp('1677-09-21 00:12:43.145225')
> ```

What is odd, and the reason I consider this to be a bug, is that when working with `GeoAccessor.from_featureclass` and dates earlier than 09/21/1677, I don't get any errors.

**Comment by achapkowski** [comment]
To represents out of bounds dates in Pandas, see:
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-oob

**Comment by bixb0012** [comment]
@achapkowski , I am trying to understand why GeoAccessor.from_featureclass works fine with pre-1677 dates but GeoAccessor.from_table doesn't?  I could understand if both did or both didn't, it is the inconsistency in behavior that I see as the issue.

**Comment by achapkowski** [comment]
@bixb0012 Table is not using cursors to create the table, it's using the da's numpy array tools.
